apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cloudnotes-dev
data:
  ENV: dev
  AWS_REGION: ap-south-1
  S3_BUCKET: cloudnotes-dev
  REDIS_URL: redis://redis:6379
  DATABASE_URL: postgresql+asyncpg://cloudnotes:cloudnotes@postgres:5432/cloudnotes
