name: CloudNotes CI

on:
    push:
        paths:
            -   "cloudnotes/**"
    pull_request:
        paths:
            - "cloudnotes/**"

jobs:
    backend-tests:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: cloudnotes/backend

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.13"

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run tests
                run: |
                    pytest
