name: CloudNotes CI

on:
    push:
        paths:
            -   "cloudnotes/**"
            -   ".github/workflows/**"
    pull_request:
        paths:
            - "cloudnotes/**"
            -   ".github/workflows/**"


jobs:
    backend-tests:
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: sqlite+aiosqlite:///./test.db
            REDIS_URL: redis://localhost:6379
            JWT_SECRET: testsecret
            AWS_REGION: ap-south-1
            S3_BUCKET: test-bucket
            ENV: test

        defaults:
            run:
                working-directory: cloudnotes/backend

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.13"

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run tests
                run: |
                    pytest

    docker-build:
        runs-on: ubuntu-latest
        needs: backend-tests

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4
            
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Build and push backend image
                run: |
                    IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/cloudnotes-backend

                    docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest ./cloudnotes/backend

                    docker push $IMAGE:${{ github.sha }}
                    docker push $IMAGE:latest

    deploy-dev:
        runs-on: ubuntu-latest
        needs: docker-build

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4
            
            -   name: Install Kubectl
                uses: azure/setup-kubectl@v4

            -   name: Configure Kubeconfig
                run: |
                    mkdir -p ~/.kube
                    echo "${{ secrets.KUBECONFIG_DEV }}" > ~/.kube/config

            -   name: Deploy backend to dev cluster
                run: |
                    IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/cloudnotes-backend:${{ github.sha }}
                    
                    kubectl set image deployment/backend \
                        backend=$IMAGE \
                        -n cloudnotes-dev

                    kubectl rollout status deployment/backend -n cloudnotes-dev
