name: CloudNotes CI

on:
    push:
        paths:
            -   "cloudnotes/**"
            -   ".github/workflows/**"
    pull_request:
        paths:
            - "cloudnotes/**"
            -   ".github/workflows/**"


jobs:
    backend-tests:
        runs-on: ubuntu-latest

        env:
            DATABASE_URL: sqlite+aiosqlite:///./test.db
            REDIS_URL: redis://localhost:6379
            JWT_SECRET: testsecret
            AWS_REGION: ap-south-1
            S3_BUCKET: test-bucket
            ENV: test

        defaults:
            run:
                working-directory: cloudnotes/backend

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v4

            -   name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: "3.13"

            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            -   name: Run tests
                run: |
                    pytest

    docker-build:
        runs-on: ubuntu-latest
        needs: backend-tests

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v$
            
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Build backend image
                run: |
                    docker build -t cloudnotes-backend:${{ github.sha }} ./cloudnotes/backend
